version: '3.8'
services:
  mysql:
    image: sjohnson2019/mysql
    build:
      context: ./db
      args:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: flask_prod
    ports:
    - "3306:3306"
  flask:
    image: sjohnson2019/flask
    build: ./flask-app
    ports:
    - "5000:5000"
    depends_on:
    - mysql
    environment:
      URI: mysql+pymysql://root:root@mysql:3306/flask_prod
      SKEY: oigh0[woifhodushvk]
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
    depends_on:
    - flask
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf