version: '3.8'
services:
  mysql:
    build: ./db
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_prod
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  flask:
    build: ./flask-app
    ports:
    - "5000:5000"
    depends_on:
    - mysql
    environment:
      URI: mysql+pymysql://admin:admin@mysql:3306/flask_prod
      SKEY: oigh0[woifhodushvk]
  nginx:
    image: nginx 
    depends_on:
    - flask
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf