version: '3.8'
services:
  mysql:
    container_name: mysql
    image: sjohnson2019/mysql
  flask:
    container_name: flask
    image: sjohnson2019/flask
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
    depends_on:
    - flask
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf